# This workflow runs edgetest on edgetest-conda @ 17:35 UTC Fridays.
# https://github.com/fdosani/run-edgetest-action

name: Run edgetest
on:
  schedule:
    - cron: '35 17 * * 3'
jobs:
  edgetest:
    runs-on: ubuntu-latest
    name: running edgetest
    steps:
      - uses: actions/checkout@0717577d45739eb3c851188b29f50ed6c0b2194e # pin@v2
        with:
          ref: main
      - id: run-edgetest
        uses: edgetest-dev/run-edgetest-action@340867ccebd0ffd7d9a91279ad36548f382123a2 # pin@v1.3
        with:
          edgetest-flags: '-c pyproject.toml --export'
          base-branch: 'main'
          skip-pr: 'false'
          python-version: '3.12'
